---
- name: Updating /etc/hosts file dynamically 
  hosts: all
  become: yes
  vars:
    ip:
      - 3.142.97.252
      - 172.22.23.66
    alias:
      - ec2-3-142-97-252.us-east-2.compute.amazonaws.com 
      - myexample.com 
  tasks:
    - name: Update /etc/hosts using Jinja2
      template:
        src: ./hosts.j2
        dest: /etc/hosts

    - name: Remove id 123
      lineinfile:
        path: /home/ec2-user/slow_response_times_dashboard.json
        regexp: 123
        state: absent
        backup: true