---
- name: Updating /etc/hosts file dynamically 
  hosts: all
  become: yes
  vars:
    ip:
      - 3.142.97.252
    alias:
      - ec2-3-142-97-252.us-east-2.compute.amazonaws.com  
  tasks:
    - name: Update /etc/hosts using Jinja2
      template:
        src: ./hosts.j2
        dest: /etc/hosts